/**
 * Mirrors the `tailwind.config` inlined by Stitch in every exported screen of the
 * "AI Saju Fortune App" project (design system: Serene Celestial Saju).
 *
 * Merged from all 24 screens. Two screens shipped a narrower fontFamily stack
 * (no "* KR" first entry) and one shipped `primary-fixed` without the leading `#`;
 * the superset below is what the design system itself defines.
 */
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#fbf9f5',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f2f0ed',
        'inverse-primary': '#bec6e0',
        'inverse-surface': '#30312e',
        'on-background': '#1b1c1a',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'on-primary-container': '#7c839b',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465b',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#785a1a',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#45464d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#539070',
        'on-tertiary-fixed': '#002112',
        'on-tertiary-fixed-variant': '#0d5135',
        outline: '#76777d',
        'outline-variant': '#c6c6cd',
        primary: '#000000',
        'primary-container': '#131b2e',
        'primary-fixed': '#dae2fc',
        'primary-fixed-dim': '#bec6e0',
        secondary: '#775a19',
        'secondary-container': '#fed488',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        surface: '#fbf9f5',
        'surface-bright': '#fbf9f5',
        'surface-container': '#efeeea',
        'surface-container-high': '#eae8e4',
        'surface-container-highest': '#e4e2de',
        'surface-container-low': '#f5f3ef',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#dbdad6',
        'surface-tint': '#565e74',
        'surface-variant': '#e4e2de',
        tertiary: '#000000',
        'tertiary-container': '#002112',
        'tertiary-fixed': '#b0f1cb',
        'tertiary-fixed-dim': '#95d4b0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        full: '9999px',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        gutter: '1rem',
        'gutter-mobile': '0.75rem',
        margin: '1.5rem',
        'margin-mobile': '1.25rem',
        'space-lg': '1.5rem',
        'space-md': '1rem',
        'space-sm': '0.5rem',
        'space-xl': '2.5rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'body-lg': ['Noto Sans KR', 'Noto Sans'],
        'body-md': ['Noto Sans KR', 'Noto Sans'],
        'body-sm': ['Noto Serif KR', 'Noto Serif'],
        'headline-lg': ['Noto Serif KR', 'Noto Serif'],
        'headline-lg-mobile': ['Noto Serif KR', 'Noto Serif'],
        'headline-md': ['Noto Serif KR', 'Noto Serif'],
        'headline-xl': ['Noto Serif KR', 'Noto Serif'],
        'headline-xl-mobile': ['Noto Serif KR', 'Noto Serif'],
        'label-lg': ['Noto Sans KR', 'Noto Sans'],
        'label-md': ['Noto Sans KR', 'Noto Sans'],
        'label-sm': ['Noto Sans KR', 'Noto Sans'],
        'title-lg': ['Noto Sans KR', 'Noto Sans'],
        'title-md': ['Noto Sans KR', 'Noto Sans'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-lg-mobile': ['22px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '500' }],
        'headline-xl': ['36px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl-mobile': ['28px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
      },
      // Not from Stitch — used by the login bottom sheet overlay.
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'sheet-up': { from: { transform: 'translateY(100%)' }, to: { transform: 'translateY(0)' } },
      },
      animation: {
        'fade-in': 'fade-in 200ms ease-out',
        'sheet-up': 'sheet-up 300ms cubic-bezier(0.32, 0.72, 0, 1)',
      },
    },
  },
  plugins: [],
};
